
- hosts: localhost
  become: false
  vars:
    source_key: "./.ssh/id_rsa"
    dest_key: "{{ lookup('env', 'HOME') }}/.ssh/id_rsa"
  pre_tasks:
   - name: Update cache
     shell: echo 'starting'
     tags:
     - install
     - core
  tasks:
  - name: install homebrew
    shell: curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh

  - include: tasks/ssh.yml

  - include: tasks/core-setup.yml

  - include: tasks/node-setup.yml

  - include: tasks/npm-packages.yml

  - include: tasks/zsh-setup.yml

  - include: tasks/nvim-setup.yml

  # - include: tasks/debugger.yml

  - include: tasks/dotfiles.yml

  - include: tasks/productivity-tools.yml
