- name: Install eslint
  npm:
    name: eslint_d
    global: yes
  tags:
    - install
    - node
    - npm
- name: Install Typescript server
  npm:
    name: typescript-language-server
    global: yes
  tags:
    - install
    - node
    - npm
- name: Install Typescript
  npm:
    name: typescript
    global: yes
  tags:
    - install
    - node
    - npm 

- name: Install TS-Node
  npm:
    name: ts-node
    global: yes
  tags:
    - install
    - node
    - npm
